services:
  mysql:
    image: mysql:8.0
    container_name: clinic-mysql
    restart: always
    environment:
      MYSQL_DATABASE: clinic_booking
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    mem_limit: 1g   
  clinic-backend:
    build:
      context: ./backend/clinic_booking
      dockerfile: Dockerfile
    container_name: clinic-backend
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/clinic_booking?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456
    ports:
      - "8089:8089"

volumes:
  mysql_data: